[General]
autoCloseIdleDaemon=true
checkForUpdates=false
contrastOpacity=188
copyPathAfterSave=false
disabledTrayIcon=false
drawColor=#f38ba8
drawThickness=3
saveAfterCopy=false
savePathFixed=false
showHelp=false
showMagnifier=true
showSidePanelButton=true
uiColor=#cba6f7
uploadHistoryMax=25

; Pendiente de preferencia personal: definir savePath si se desea un destino fijo.
